### ISSUE TITLE
Error while starting up demo app

### ISSUE THREAD

**Issue by brentmc79** [balupton/nowpad#6]
Upon following the instructions in the README, I get the following error:

```
$ coffee bin/nowpad.coffee 
Error: Cannot find module '/Users/brentmc79/Documents/Code/oss/nowpad/bin/../examples/ace/server.js'
    at Function._resolveFilename (module.js:317:11)
    at Function._load (module.js:262:25)
    at require (module.js:346:19)
    at Object.<anonymous> (/Users/brentmc79/Documents/Code/oss/nowpad/bin/nowpad.coffee:2:3)
    at Object.<anonymous> (/Users/brentmc79/Documents/Code/oss/nowpad/bin/nowpad.coffee:3:4)
    at Module._compile (module.js:402:26)
    at Object.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script.js:57:25)
    at /usr/local/lib/node_modules/coffee-script/lib/command.js:147:29
    at /usr/local/lib/node_modules/coffee-script/lib/command.js:115:26
    at [object Object].<anonymous> (fs.js:107:5)
```

**Comment by balupton** [comment]
https://github.com/balupton/nowpad/issues/11
